openapi: 3.0.0
info:
  title: Distribution Service Api
  version: 1.0.0
servers:
  - url: /api/v1/
  - url: https://example-qa.adara.com/api/v1/
  - url: https://example-prod.adara.com/api/v1/
paths:
  /example:
    get:
      operationId: framework.routes.api.example
      summary: example get endpoint
      security:
        - oauth2:
            - get:example
      tags:
        - example
      responses:
        200:
          $ref: '#/components/responses/GetPlatforms'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      x-tokenInfoFunc: framework.routes.core.auth.verify_token
      flows:
        clientCredentials:
          tokenUrl: /core/v1.0/oauth/token
  responses:
    GetPlatforms:
      description: example description
      content:
        application/json:
          schema:
            type: object
            properties:
              active:
                type: boolean